services:
  # Spatial Database
  db:
    image: postgis/postgis:15-3.3
    container_name: sixsense_postgis
    restart: always
    environment:
      POSTGRES_USER: sixsense_user
      POSTGRES_PASSWORD: sixsense_password
      POSTGRES_DB: sixsense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # In-Memory Cache & Event Store
  redis:
    image: redis:7-alpine
    container_name: sixsense_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: